---
title: "about"
author: "Anna Leach"
date: "2026-09-22"
output: html_document
---

This project was developed by Team Soul For INFO 526 - Data Analysis and Visualization at the University of Arizona, taught by Dr. Anna R. Leach. The team is comprised of the following team members.

Team member 1: One sentence description of Team member 1 (e.g., year, major, etc.).
My name is Julian, I am in my first semester studying data science.  
Team member 2: One sentence description of Team member 2 (e.g., year, major, etc.).
My name is Jesus, I am a second year PhD student in Mining Engineering

Team member 3: One sentence description of Team member 3 (e.g., year, major, etc.).
My name is Sanjana,Fall 2026 student in Masters in data Science who is interested in data visualization,analysis and learn new dta scienec techniques
Team member 4: One sentence description of Team member 4 (e.g., year, major, etc.).
My name is Jacob. I am in my first semester studying machine learning, but that may change. 
